# Habilitar AndroidX
android.useAndroidX=true

# Habilitar Jetifier (para compatibilidad con librerías antiguas)
android.enableJetifier=true

# Optimizaciones de compilación
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true

# Kotlin
kotlin.code.style=official
