name: Build APK CASOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Accept Android SDK licenses
        run: |
          export ANDROID_SDK_ROOT=/usr/local/lib/android/sdk
          yes | $ANDROID_SDK_ROOT/tools/bin/sdkmanager --licenses || true
          yes | $ANDROID_SDK_ROOT/tools/bin/sdkmanager --licenses --no_https || true

      - name: Install SDK components
        run: |
          export ANDROID_SDK_ROOT=/usr/local/lib/android/sdk
          $ANDROID_SDK_ROOT/tools/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Clean project
        run: ./gradlew clean

      - name: Build APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: CASOS-APK
          path: app/build/outputs/apk/debug/app-debug.apk
